In [5]:
import numpy
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]  # create a list 
a = numpy.array(l)  # convert a list to an array 
# print(a) 
# a.shape 
# print(a.dtype)  # get type of an array 
# or directly as matrix
# M = numpy.array([[1, 2], [3, 4]])
# M.shape
# M.dtype

(2, 2)

In [16]:
print(a) 
# print(a[0])  # this is just like a list of lists 
# print(a[0,2])  # arrays can be given comma separated indices 
# print(a[2,1:3])  # and slices 
print(a[:,1]) 

[[1 2 3]
 [3 6 9]
 [2 4 6]]
[2 6 4]
